### PR TITLE
g11n + L10n fr

### PR DESCRIPTION
**Pull request by tdd**
Hey Sebastian,

First, thanks for Planet Proto, it's a great workshop! One of the few that uses the boilerplate system, too, bravo!

Related to the nodeschool/organizers#64 efforts, I'm in the process of upgrading most workshops to the latest versions of the infra modules (`workshopper`, `workshopper-exercise` and `workshopper-boilerplate`) and adding `fr` L10n for them.

This is the result for Planet Proto. It's been entirely tested again, in English and French, and works well.

I also took the liberty to use variations of the reference solution codes that closely mirrors the boilerplates; I suspect these evolved post-solution, and I find it's easier for "students" to read the solutions when the comments and structure  from the boilerplates remains. I'd be happy to do that for the ref English solution too if you like this idea.

Would you consider merging that in and bumping on npm before Saturday?  This would make it easier for French attendees of NodeSchool Paris #1 to tackle it if they feel English adds too much friction.

Naturally, I'm available for any questions or discussion on this.

Best,

### CODE REVIEW

**Comment by sporto** [comment]
This is great, thanks

**Comment by tdd** [comment]
Hey Sebastian,

Yay :tada: wonderful to see this moving forward. Don't worry about not making it in time for last Saturday, the few people playing with `planetproto` there favored English anyway.

Looking forward to the updated version on npm. Would you be kind enough to notify me here when it's out?

Thanks again!

**Comment by sporto** [comment]
@tdd I have published the latest version to npm with the french localisation

**Comment by tdd** [comment]
Kickass, thank you! :tada:

**Pull request merged**
